import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

// Assemble our small ESM factory modules into fixed-name runtime payloads.
// This deliberately supports named imports/exports only and rejects cycles.
// Installed pre-0.31 upgraders copy fixed filenames, so source modularity must
// not add dependencies to those deployed entrypoints.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const targets = [['src/conversation-relay/conversation-turn-relay.mjs', 'conversation-turn-relay.mjs'], ['src/server/server.mjs', 'aru-selfhost-stub.mjs']];
for (const [input, output] of targets) {
  const nodes = new Map(), modules = new Map(), active = new Set(), chunks = [];
  function visit(path) {
    if (active.has(path)) throw new Error(`Runtime module cycle: ${path}`);
    if (modules.has(path)) return modules.get(path);
    active.add(path);
    const id = `module${modules.size}`;
    modules.set(path, id);
    let source = readFileSync(path, 'utf8');
    const exported = [];
    source = source.replace(/import\s*\{([\s\S]*?)\}\s*from\s*["']([^"']+)["'];?/g, (_, bindings, specifier) => {
      let dependency;
      if (specifier.startsWith('node:') || specifier.startsWith('../../')) {
        if (specifier.startsWith('../../')) specifier = './' + resolve(dirname(path), specifier).slice(root.length + 1);
        if (!nodes.has(specifier)) nodes.set(specifier, `node${nodes.size}`);
        dependency = nodes.get(specifier);
      } else if (specifier.startsWith('./')) {
        dependency = visit(resolve(dirname(path), specifier));
      } else throw new Error(`Unsupported runtime import: ${specifier}`);
      return `const {${bindings.replace(/\bas\b/g, ':')}} = ${dependency};`;
    });
    source = source.replace(/export\s*\{([^}]+)\};?/g, (_, names) => {
      exported.push(...names.split(',').map(x => x.trim()).filter(Boolean));
      return '';
    });
    source = source.replace(/export\s+(const|function|class)\s+(\w+)/g, (_, kind, name) => {
      exported.push(name); return `${kind} ${name}`;
    });
    if (/^\s*(import|export)\s/m.test(source)) throw new Error(`Unsupported module syntax: ${path}`);
    chunks.push(path === resolve(root, input) && output === 'aru-selfhost-stub.mjs' ? source.trim() : `// ${path.slice(root.length + 1)}\nconst ${id} = (() => {\n${source.trim()}\nreturn { ${[...new Set(exported)].join(', ')} };\n})();`);
    active.delete(path);
    return id;
  }
  const entry = visit(resolve(root, input));
  const source = (output === 'aru-selfhost-stub.mjs' ? '#!/usr/bin/env node\n' : '') + '// Generated by tools/build-runtime.mjs. Edit src/ and regenerate.\n'
    + [...nodes].map(([name, id]) => `import * as ${id} from '${name}';`).join('\n') + '\n\n'
    + chunks.join('\n\n') + (output === 'aru-selfhost-stub.mjs' ? '\n' : `\n\nexport const { createConversationTurnRelay, SUPPORTED_CONVERSATION_TURN_PROTOCOLS } = ${entry};\n`);
  const destination = resolve(root, output);
  if (process.argv.includes('--check')) {
    if (readFileSync(destination, 'utf8') !== source) throw new Error(`Stale generated runtime: ${output}`);
  } else writeFileSync(destination, source);
}
